// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: cluster/rpc/replication.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            uint32                 `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALRecord) Reset() {
	*x = WALRecord{}
	mi := &file_cluster_rpc_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALRecord) ProtoMessage() {}

func (x *WALRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_rpc_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALRecord.ProtoReflect.Descriptor instead.
func (*WALRecord) Descriptor() ([]byte, []int) {
	return file_cluster_rpc_replication_proto_rawDescGZIP(), []int{0}
}

func (x *WALRecord) GetOp() uint32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *WALRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WALRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *WALRecord             `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_cluster_rpc_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_rpc_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_cluster_rpc_replication_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicateRequest) GetRecord() *WALRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_cluster_rpc_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_rpc_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_cluster_rpc_replication_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_cluster_rpc_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_rpc_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_cluster_rpc_replication_proto_rawDescGZIP(), []int{3}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_cluster_rpc_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_rpc_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_cluster_rpc_replication_proto_rawDescGZIP(), []int{4}
}

var File_cluster_rpc_replication_proto protoreflect.FileDescriptor

const file_cluster_rpc_replication_proto_rawDesc = "" +
	"\n" +
	"\x1dcluster/rpc/replication.proto\x12\vreplication\"C\n" +
	"\tWALRecord\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\rR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"B\n" +
	"\x10ReplicateRequest\x12.\n" +
	"\x06record\x18\x01 \x01(\v2\x16.replication.WALRecordR\x06record\"-\n" +
	"\x11ReplicateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10HeartbeatRequest\"\x13\n" +
	"\x11HeartbeatResponse2\xac\x01\n" +
	"\x12ReplicationService\x12J\n" +
	"\tReplicate\x12\x1d.replication.ReplicateRequest\x1a\x1e.replication.ReplicateResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.replication.HeartbeatRequest\x1a\x1e.replication.HeartbeatResponseB\x11Z\x0fcluster/rpc;rpcb\x06proto3"

var (
	file_cluster_rpc_replication_proto_rawDescOnce sync.Once
	file_cluster_rpc_replication_proto_rawDescData []byte
)

func file_cluster_rpc_replication_proto_rawDescGZIP() []byte {
	file_cluster_rpc_replication_proto_rawDescOnce.Do(func() {
		file_cluster_rpc_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_rpc_replication_proto_rawDesc), len(file_cluster_rpc_replication_proto_rawDesc)))
	})
	return file_cluster_rpc_replication_proto_rawDescData
}

var file_cluster_rpc_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cluster_rpc_replication_proto_goTypes = []any{
	(*WALRecord)(nil),         // 0: replication.WALRecord
	(*ReplicateRequest)(nil),  // 1: replication.ReplicateRequest
	(*ReplicateResponse)(nil), // 2: replication.ReplicateResponse
	(*HeartbeatRequest)(nil),  // 3: replication.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: replication.HeartbeatResponse
}
var file_cluster_rpc_replication_proto_depIdxs = []int32{
	0, // 0: replication.ReplicateRequest.record:type_name -> replication.WALRecord
	1, // 1: replication.ReplicationService.Replicate:input_type -> replication.ReplicateRequest
	3, // 2: replication.ReplicationService.Heartbeat:input_type -> replication.HeartbeatRequest
	2, // 3: replication.ReplicationService.Replicate:output_type -> replication.ReplicateResponse
	4, // 4: replication.ReplicationService.Heartbeat:output_type -> replication.HeartbeatResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cluster_rpc_replication_proto_init() }
func file_cluster_rpc_replication_proto_init() {
	if File_cluster_rpc_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_rpc_replication_proto_rawDesc), len(file_cluster_rpc_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_rpc_replication_proto_goTypes,
		DependencyIndexes: file_cluster_rpc_replication_proto_depIdxs,
		MessageInfos:      file_cluster_rpc_replication_proto_msgTypes,
	}.Build()
	File_cluster_rpc_replication_proto = out.File
	file_cluster_rpc_replication_proto_goTypes = nil
	file_cluster_rpc_replication_proto_depIdxs = nil
}
